### ISSUE TITLE
Datei Vergessen und Fehler bei Block wahl

### ISSUE THREAD

**Issue by DragonfireHD** [Ceepkev77/MyPlotMerge#4]
[22:25:39] [Server thread/CRITICAL]: InvalidArgumentException: "Block meta value 44 is out of bounds" (EXCEPTION) in "src/pocketmine/block/BlockFactory" at line 393

Du hast bei WandSubCommand eine Datei vergessen du musst 
use MyPlot/WandChest;

**Comment by Ceepkev77** [comment]
Muss ich noch fixen

**Comment by DragonfireHD** [comment]
Habs gefixt das mit der datei nur aber wenn man die Blöcke auswählt oder zieht dann wird man rausgeworfen achja kannst du kich vielleicht enblocken?? bei DC

**Comment by Ceepkev77** [comment]
Hab dich net geblockt musst fa senden

**Comment by DragonfireHD** [comment]
Hab dir die Pull request gesendet die andere mit Doppel rand war falsch das mit WandChest war richtig
